#!/usr/bin/env python3
"""
pack_manifest.py — emit a root-level MANIFEST.md for a behavior-baseline pack, so the
two-level folder layout (project-level 00-99 + per-operation 01-11) is self-documenting
and nothing has to be hunted for. Regenerate every run.

Usage: pack_manifest.py <pack-dir>  ->  writes <pack-dir>/MANIFEST.md
"""
import os, sys, glob, datetime

LEGEND = {
    "00-run-manifest": "run summary, stack profiles, adapter capability coverage",
    "01-topology": "dependency graph, error-code / config / datastore / exception catalogs",
    "02-entrypoints": "entry-point catalog (incl. lifecycle entry points)",
    "03-operations": "one sub-folder per business operation (see per-operation layout below)",
    "04-coverage": "closure-driven coverage proof (reachable/visited/unreached)",
    "90-evidence": "MECHANICAL tool output (JSON) — ground truth, reproducible",
    "91-gaps": "OPEN capability gaps only (resolution history is in git)",
    "99-completeness": "completeness report",
}
OP_LEGEND = {
    "01-scope": "operation scope + entry points",
    "03-flows": "end-to-end flow, flow-graph.mmd, sequence.md, sub-flows",
    "04-decisions-effects": "decisions, state/integration effects, branch-completeness",
    "05-rules-semantics": "rule catalog, semantic resolutions, value lineage",
    "06-behavior": "current-behavior (CBH), behavior families",
    "07-bdd": "<operation>.feature (Gherkin projection)",
    "10-gaps": "behavior-linked gaps + correctness observations (open only)",
    "11-confidence": "completeness & confidence for this operation",
}

def tree(root, prefix="", maxdepth=2, depth=0):
    if depth > maxdepth:
        return []
    entries = sorted(e for e in os.listdir(root) if not e.startswith("."))
    dirs = [e for e in entries if os.path.isdir(os.path.join(root, e))]
    lines = []
    for i, name in enumerate(dirs):
        last = i == len(dirs) - 1
        conn = "└── " if last else "├── "
        note = LEGEND.get(name) or OP_LEGEND.get(name) or ""
        lines.append(f"{prefix}{conn}{name}/" + (f"  — {note}" if note else ""))
        sub = os.path.join(root, name)
        # don't expand every operation; show one as the template
        if name == "03-operations":
            ops = sorted(d for d in os.listdir(sub) if os.path.isdir(os.path.join(sub, d)))
            for j, op in enumerate(ops):
                oplast = j == len(ops) - 1
                oc = "    └── " if oplast else "    ├── "
                lines.append(f"{prefix}{'    ' if last else '│   '}{oc}{op}/")
            break_note = True
        elif depth < maxdepth:
            lines += tree(sub, prefix + ("    " if last else "│   "), maxdepth, depth + 1)
    return lines

def main():
    pack = sys.argv[1] if len(sys.argv) > 1 else "."
    pid = os.path.basename(os.path.abspath(pack))
    ops = sorted(os.path.basename(d) for d in glob.glob(os.path.join(pack, "03-operations", "*"))
                 if os.path.isdir(d))
    L = [f"# {pid} — behavior baseline: structure manifest", ""]
    L.append("Auto-generated by system-atlas (`tools/pack_manifest.py`). Two levels of numbered")
    L.append("folders: **project-level** (`00`–`99`) and **per-operation** (`01`–`11`, nested under")
    L.append("each `03-operations/<Operation>/`). Regenerate every run — do not hand-edit.")
    L.append("")
    L.append("## Project layout")
    L.append("```")
    L.append(f"{pid}/")
    L += tree(pack, "", maxdepth=1)
    L.append("```")
    L.append("")
    L.append("## Per-operation layout (inside each `03-operations/<Operation>/`)")
    L.append("```")
    L.append("<Operation>/")
    keys = list(OP_LEGEND.items())
    for i, (k, v) in enumerate(keys):
        conn = "└── " if i == len(keys) - 1 else "├── "
        L.append(f"{conn}{k}/  — {v}")
    L.append("```")
    L.append("")
    L.append(f"## Operations in this pack ({len(ops)})")
    for op in ops:
        L.append(f"- `{op}`")
    L.append("")
    L.append("## Reading the pack")
    L.append("- **Start:** `application-behavior-summary.md`")
    L.append("- **Canonical data:** the `*.yaml` files (structured, queryable). Markdown files are")
    L.append("  human projections/summaries that reference them.")
    L.append("- **Ground truth vs synthesis:** `90-evidence/*.json` is mechanical tool output;")
    L.append("  per-operation `*.yaml/*.md` are runtime synthesis grounded in it (enforced by pack_lint).")
    open(os.path.join(pack, "MANIFEST.md"), "w").write("\n".join(L) + "\n")
    print(f"wrote {os.path.join(pack, 'MANIFEST.md')} ({len(ops)} operations)")

if __name__ == "__main__":
    main()
